language: java
script: mvn test
cache:
  directories:
    - ~/.m2/repository
before_install:
  - openssl aes-256-cbc -K $encrypted_79917fed2cf8_key -iv $encrypted_79917fed2cf8_iv -in codesigning.asc.enc -out ./travis/codesigning.asc -d